In [2]:
class Solution:
    def spiralOrder(self, matrix):
        row = len(matrix)
        col = len(matrix[0])

        start_row = 0
        start_col = 0

        end_row = row
        end_col = col

        curr_row = 0
        curr_col = col - 1

        spiral = []

        while(len(spiral) < row*col):
            
            #Left -> Right
            for i in range(curr_row, end_col):
                spiral.append(matrix[curr_row][i])
            curr_row += 1
            end_col -= 1

            if len(spiral) == row*col:
                break
            
            # Top right -> Top down
            for i in range(curr_row, end_row):
                spiral.append(matrix[i][curr_col])
            curr_col -= 1
            end_row -= 1

            if len(spiral) == row*col:
                break
            
            #Bottom Right -> Bottom Left
            for i in range(curr_col, start_col-1, -1):
                spiral.append(matrix[end_row][i])
            start_col += 1

            if len(spiral) == row*col:
                break
            
            #Bottom left -> Top Left
            for i in range(end_row-1, start_row, -1):
                spiral.append(matrix[i][start_col-1])
            start_row += 1
        return spiral

        for row_index in range(len(mat)):
            for col_index in range(len(mat[0])):

In [ ]:
class Solution:
    def matrixReshape(self, mat, r, c):

        if not mat or r*c != len(mat) * len(mat[0]):
            return mat
     
        l = [[0 for _ in range(c)] for _ in range(r)]

        n=len(mat[0])

        i=0
        while i < r*c:
            l[i//c][i%c] = mat[i//n][i%n]  
            i+=1
        return l

In [11]:
import numpy as np
# The type of arrays: np.ndarray
# pip3 install numpy

curArray1 = np.array(((3, 20, 5), [1, 400, 2]), dtype=np.int16)
curArray6 = np.linspace(1,3,12)
print(f'Array with equally spaced values:\n{curArray6}')

curArray7 = np.logspace(1,2,10)
print(f'Array with rqually spaced values in the logarithmic scale:\n{curArray7}')
print(f'Element Distance: {np.log10(curArray7[3])- np.log10(curArray7[2])}')
print(f'Element Distance: {np.log10(curArray7[-1])- np.log10(curArray7[-2])}')

print(f'Type of Array: {type(curArray1)}')
print(f'Number of Dimensions (ndim): {curArray1.ndim}')
print(f'Number of Elements (size): {curArray1.size}')
print(f'Number of Rows and Columns (shape as a tuple): {curArray1.shape}')
print(f'Item Size (in Bytes): {curArray1.itemsize}')
print(f'Data Type: {curArray1.dtype}')

print(f'Minimum Value: {curArray1.min()}')
print(f'Maximum Value: {curArray1.max(axis=0)}') # across rows
print(f'Sum: {curArray1.sum(axis=1)}') # across columns
print(f'Average: {curArray1.mean()} | {curArray1.mean(axis=0)} | {curArray1.mean(axis = 1)}')
print(f'Cumulative Sum:\n{curArray1.cumsum(axis=1)}')
print(f'Sorting Values:\n{np.sort(curArray1, axis=1)}')

Array with equally spaced values:
[1.         1.18181818 1.36363636 1.54545455 1.72727273 1.90909091
 2.09090909 2.27272727 2.45454545 2.63636364 2.81818182 3.        ]
Array with rqually spaced values in the logarithmic scale:
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
Element Distance: 0.11111111111111094
Element Distance: 0.11111111111111116
Type of Array: <class 'numpy.ndarray'>
Number of Dimensions (ndim): 2
Number of Elements (size): 6
Number of Rows and Columns (shape as a tuple): (2, 3)
Item Size (in Bytes): 2
Data Type: int16
Minimum Value: 1
Maximum Value: [  3 400   5]
Sum: [ 28 403]
Average: 71.83333333333333 | [  2.  210.    3.5] | [  9.33333333 134.33333333]
Cumulative Sum:
[[  3  23  28]
 [  1 401 403]]
Sorting Values:
[[  3   5  20]
 [  1   2 400]]


In [24]:
randArray1 = np.random.randint(10, 20, (5,10), dtype=np.int16)
print(f'Random Integer Matrix Before Change:\n{randArray1}')
# print(randArray1[3,-4])
# print(randArray1[1:4:2,2:8:3])
# print(randArray1[-3])
# print(randArray1[:,4::3])
# randArray1[1:4:2,2::3] = -100
# randArray1[3:,:4:2] = -200
# print(f'Random Integer Matrix After Change:\n{randArray1}')
# print(f'{randArray1[1:4:2]}')

print(f'Array Indexing 1:\n{randArray1[[0,2,-1],[-2,6,2]]}')
print(f'Array Indexing 2:\n{randArray1[[[0,4,1],[3,2,3]],[[2,5,2],[-1,0,-1]]]}')

randArray1[[2,3],[4,0]] = -200
randArray1[[1,-1]] = -500
print(f'Array Modification Using Advanced Indexing:\n{randArray1}')
np.array([(-2, 0, 6, -9), [-6, 3, 0, 10]])
print(np.array([(-2, 0, 6, -9), [-6, 3, 0, 10]]).dtype)
print(np.arange(1, 20, 2).reshape(5,2)[ : : -1])

Random Integer Matrix Before Change:
[[11 18 17 18 12 14 12 15 13 14]
 [12 18 17 11 19 11 11 16 11 19]
 [10 14 17 18 14 10 13 13 14 14]
 [16 11 18 11 16 16 19 16 13 17]
 [15 18 10 12 13 12 18 11 18 18]]
Array Indexing 1:
[13 13 10]
Array Indexing 2:
[[17 12 17]
 [17 10 17]]
Array Modification Using Advanced Indexing:
[[  11   18   17   18   12   14   12   15   13   14]
 [-500 -500 -500 -500 -500 -500 -500 -500 -500 -500]
 [  10   14   17   18 -200   10   13   13   14   14]
 [-200   11   18   11   16   16   19   16   13   17]
 [-500 -500 -500 -500 -500 -500 -500 -500 -500 -500]]
int64
[[17 19]
 [13 15]
 [ 9 11]
 [ 5  7]
 [ 1  3]]
