In [7]:
a = 'to take the exam or not to take the exam that is the question'

print(a.count('the', 9))
print(a.rfind('Fri'))
print(a.rindex('to'))
print(a.split(' the ', 2))
print('*'.join(a[12:16]))
print(''.join(a[12:16]))

2
-1
24
['to take', 'exam or not to take', 'exam that is the question']
e*x*a*m
exam


In [27]:
import numpy as np
a = np.array([(-2, 0, 6, -9), [-6, 3, 0, 10]], dtype=np.int16)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.cumsum())
print(a.max(axis=0))
print(a[:, ::2])
print(a[-1, 0])
print("")
print(a[ [[-1, 0], [0, 1]], [[2, 3],[-1, 1]] ])




2
(2, 4)
8
2
[ -2  -2   4  -5 -11  -8  -8   2]
[-2  3  6 10]
[[-2  6]
 [-6  0]]
-6

[[ 0 -9]
 [-9  3]]


In [29]:
A = np.arange(0, 12, 2).reshape(2,3)
print(A)

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
def is_valid(s):
    stack = []
    for char in s:
        if char in "({[":
            stack.append(char)
        else:
            if not stack:
                return False
            if char == ")" and stack[-1] != "(":
                return False
            if char == "}" and stack[-1] != "{":
                return False
            if char == "]" and stack[-1] != "[":
                return False
            stack.pop()
    return not stack

In [ ]:
def matrix_block_sum(mat, k):
    m, n = len(mat), len(mat[0])
    answer = [[0] * n for _ in range(m)]
    
    # Calculate the cumulative sum along rows
    for i in range(m):
        for j in range(1, n):
            mat[i][j] += mat[i][j-1]
    
    # Calculate the cumulative sum along columns
    for j in range(n):
        for i in range(1, m):
            mat[i][j] += mat[i-1][j]
    
    # Calculate the sum for each window
    for i in range(m):
        for j in range(n):
            r1, c1 = max(i - k, 0), max(j - k, 0)
            r2, c2 = min(i + k, m-1), min(j + k, n-1)
            answer[i][j] = mat[r2][c2]
            if r1 > 0:
                answer[i][j] -= mat[r1-1][c2]
            if c1 > 0:
                answer[i][j] -= mat[r2][c1-1]
            if r1 > 0 and c1 > 0:
                answer[i][j] += mat[r1-1][c1-1]
    
    return answer
