In [17]:
word = "joe mama boi dedicated"


str_list = word.split(" ")
out_str_list = list()
for item in str_list:
    if 'b' == item[0]:
        out_str_list.append(item)
    if 'ed' == item[-2:]:
        out_str_list.append(item)

print(out_str_list)

in_str = "This is a really big string word boned"
word_list = in_str.split(" ")

# One way 
wanted_words = list()
for cur_word in word_list:
    if cur_word.lower()[0] == 'b' or cur_word.lower()[-2:] == "ed":
        wanted_words.append(cur_word)
print(wanted_words)

# second way
wanted_words = list()
for cur_word in word_list:
    if cur_word.lower().startswith('b') or cur_word.lower().endswith("ed"):
        wanted_words.append(cur_word)
print(wanted_words)


# second way
wanted_words = list()
wanted_words = [(cur_word) for cur_word in word_list \
    if cur_word.lower().startswith('b') or cur_word.lower().endswith("ed")]

print(wanted_words)
print(' * '.join(wanted_words))




['boi', 'dedicated']
['big', 'boned']
['big', 'boned']
['big', 'boned']
big * boned


In [18]:
num_list = [str(k) for k in range(10)]

print(', '.join(num_list))

0, 1, 2, 3, 4, 5, 6, 7, 8, 9


In [48]:
import numpy as np
# pip3 install numpy
# NumPy Library is the Python n-dimensional array implemenetation for an array-oriented-programming.
# NumPy Universal Functions contain alot of mathematical functions.

#Create arrays and its desired dimensions have to be a tuple
curArray1 = np.array(((1,20, 2), [3, 40, 5]), dtype=np.int16)
print(f'Array created from a list or tuple:\n{curArray1}')

curArray2 = np.zeros(4)
print(f'Array with all elements set to zeros:\n{curArray2}')

curArray3 = np.ones((3,4))
print(f'Array with all elements set to ones:\n{curArray3}')

curArray4 = np.full((4,5), -10)
print(f'Array with all elements set to -10:\n{curArray4}')

curArray5 = np.arange(1, 10)
print(f'Array with a all elements set to a range of 1-9:\n {curArray5}')

curArray6 = np.linspace(1, 3, 6)
print(f'Array with equally spaced values seen in math:\n {curArray6}')

curArray7 = np.logspace(1, 2, 10)
print(f'Array with equally spaced values in the logarithmic scale:\n{curArray7}')
print(f'Element Distance:\n{np.log10(curArray7[3])- np.log10(curArray7[2])}')
print(f'Element Distance:\n{np.log10(curArray7[-1])- np.log10(curArray7[-2])}')


Array created from a list or tuple:
[[ 1 20  2]
 [ 3 40  5]]
Array with all elements set to zeros:
[0. 0. 0. 0.]
Array with all elements set to ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with all elements set to -10:
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
Array with a all elements set to a range of 1-9:
 [1 2 3 4 5 6 7 8 9]
Array with equally spaced values seen in math:
 [1.  1.4 1.8 2.2 2.6 3. ]
Array with equally spaced values in the logarithmic scale:
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
Element Distance:
0.11111111111111094
Element Distance:
0.11111111111111116


In [50]:
print(curArray1)
print(f'Type of Array: {type(curArray1)}')
print(f'Number of Dimensions: {curArray1.ndim}')
print(f'Size of Array: {curArray1.size}')
print(f'Shape of Array as a Tuple for Rows and Columns: {curArray1.shape}')
print(f'ItemSize of Array (in 2 Bytes): {curArray1.itemsize}')

# axis = 1 - rows
# axis = 0 - columns
print(f'Minimum Value: {curArray1.min()}')
print(f'Maximium Value: {curArray1.max(axis=1)}')
print(f'Sum: {curArray1.sum(axis=0)}')
print(f'Average: {curArray1.mean()}')
# adds them cumulatively in each row or col
# in - [1, 20, 2]
# in - [1, 21, 23]
print(f'Cumulative Sum: {curArray1.cumsum(axis=1)}')
print(f'Sorting Values: {np.sort(curArray1, axis=0)}')

[[ 1 20  2]
 [ 3 40  5]]
Type of Array: <class 'numpy.ndarray'>
Number of Dimensions: 2
Size of Array: 6
Shape of Array as a Tuple for Rows and Columns: (2, 3)
ItemSize of Array (in 2 Bytes): 2
Minimum Value: 1
Maximium Value: [20 40]
Sum: [ 4 60  7]
Average: 11.833333333333334
Cumulative Sum: [[ 1 21 23]
 [ 3 43 48]]
Sorting Values: [[ 1 20  2]
 [ 3 40  5]]


In [59]:
# Generate Random Arrays
randArray1 = np.random.rand(5, 2)
print(f'Uniform Random Matrix of 0-1:\n {randArray1}')

randArray2 = np.random.randint(10, 20, size=(2, 3), dtype=np.int8)
print(f'Prints a random matix with a range of [low, high]: {randArray2}')

# bell curve of random values
randArray3 = np.random.randn(2, 3)
print(f'Random matrix from a standard normal distribution: {curArray1.size}')
print(f'Verify Average: {randArray3.std()}')
print(f'Verify Standard Deviation: {randArray3.mean()}')

curMean, curStd = 1, 3
randArray31 = curMean + curStd * np.random.randn(2,3)
#print(f'Random matrix from a standard normal distribution: {randArray31.size()}')
#print(f'Verify Average: {randArray31.std()}')
#print(f'Verify Standard Deviation: {randArray31.mean()}')

randArray4 = np.floor(20*np.random.rand(5,2))
print(f'Integer Random Matrix:\n{randArray4}')

bits = np.round(np.random.rand(10))
symbols = bits * 2 - 1 #BPSK Method
print(f'Bits: {bits}')
print(f'Symbols: {symbols}')

# Construct a new Generator with an optional seed to initialize the default BitGenerator
curRng = np.random.default_rng(2253)
randArray5 = curRng.random((4,5))
print(f'Uniform Random Matrix of RNG Generator: {curArray1.max(axis=1)}')

randArray6 = curRng.integers(10, 20, (3, 4), endpoint=True)

curMean, curStd = 1, 3
randArray7 = curRng.normal(loc=curMean, scale=curStd, size=(3000, 4000))
print(f'Average: {abs(curMean - randArray7.mean())}')
print(f'Standard Deviation: {abs(curStd - curArray1.std())}')


Uniform Random Matrix of 0-1:
 [[0.76008636 0.71586038]
 [0.93944519 0.05634853]
 [0.08904679 0.84249232]
 [0.73766415 0.40114518]
 [0.61444221 0.1429372 ]]
Prints a random matix with a range of [low, high]: [[13 13 18]
 [11 18 13]]
Random matrix from a standard normal distribution: 6
Verify Average: 1.0757960495463996
Verify Standard Deviation: -0.5133702377884887
Integer Random Matrix:
[[ 2.  0.]
 [ 1.  0.]
 [17.  6.]
 [ 1.  5.]
 [ 5.  2.]]
Bits: [1. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
Symbols: [ 1. -1.  1.  1. -1.  1.  1.  1. -1.  1.]
Uniform Random Matrix of RNG Generator: [20 40]
r: [ 4 60  7]
Average: 11.833333333333334
Cumulative Sum: [[ 1 21 23]
 [ 3 43 48]]
Sorting Values: [[ 1 20  2]
 [ 3 40  5]]


In [1]:
import numpy as np
# NumPy (Numerical Python)
# - Math: 
# - Bit manipulations
# - Trigonometry
# - Comparison
# - Floating Point

# 4 bits 0 - 15
# 16; 10000
# 17: 10001

# Array Indexing and Slicing 
randArray1 = np.random.randint(10, 201, (5,10), dtype=np.uint8)
print(f'Random Integers Matrix \n {randArray1}')

print(randArray1[1:3, 3:6])
print(randArray1[1:4:2, 3:6])
# rows: 1,3
# col: 2,5
print(randArray1[1::2, 2::3])

print(randArray1[1:,4::3])

# print the values in the row
print(randArray1)

# element at row 0 and col 2 
# element at row 2 and col 6
print(f'Array Indexing: n\ {randArray1[[0, 2], [2,6]]}')

print(f'Array Indexing: n\ {randArray1[[0, 2, -1], [2,6, 2]]}')


# yellow bracket on right is row notation
# yellow bracket on left is col notation
print(f'Array Indexing: n\ {randArray1[[[0, 4, 1], [3,2, 3]], [[2, 5, 2], [-1, 0, -1]]]}')

randArray1[[2, 3], [4,0]] = -200
print(f'Array Modification: n\ {randArray1}')
randArray1[1, -1] = -200
print(f'Array Modification: n\ {randArray1}')


curRng = np.random.default_rng(1)
curMean, curStd = 2, np.sqrt(3)
randArray2 = curRng.normal(loc=curMean, scale=curStd, size=(5,6))
print(f'Random Matrix with Normal Distribution n\{randArray2}')


Random Integers Matrix 
 [[166  71  53  47  44  83  31 166 159 120]
 [162 140  46  96 164  12 161 193  95  23]
 [ 93  64  29 174  17  20  32 171 175 157]
 [182 145  12 133 189 111 161  42  22 153]
 [142  20 136 111 154 200  13 122 131 163]]
[[ 96 164  12]
 [174  17  20]]
[[ 96 164  12]
 [133 189 111]]
[[ 46  12  95]
 [ 12 111  22]]
[[164 193]
 [ 17 171]
 [189  42]
 [154 122]]
[[166  71  53  47  44  83  31 166 159 120]
 [162 140  46  96 164  12 161 193  95  23]
 [ 93  64  29 174  17  20  32 171 175 157]
 [182 145  12 133 189 111 161  42  22 153]
 [142  20 136 111 154 200  13 122 131 163]]
Array Indexing: n\ [53 32]
Array Indexing: n\ [ 53  32 136]
Array Indexing: n\ [[ 53 200  46]
 [153  93 153]]
Array Modification: n\ [[166  71  53  47  44  83  31 166 159 120]
 [162 140  46  96 164  12 161 193  95  23]
 [ 93  64  29 174  56  20  32 171 175 157]
 [ 56 145  12 133 189 111 161  42  22 153]
 [142  20 136 111 154 200  13 122 131 163]]
Array Modification: n\ [[166  71  53  47  44  83  31 166