In [1]:
import numpy as np 

print(f'[{1976.0236:*^+14,.5f}]')

[*+1,976.02360*]


In [11]:
my_str = 'to be or not to be that is the question'
print(my_str.rindex('be'))

print("man" <= "Manchester")

print("a man Was happy".title())

print(my_str.count('to', 1, 14))

print(my_str.index("the"))
print(my_str.rindex("the"))

16
False
A Man Was Happy
0
27
27


In [13]:
my_str = "10, 20, 30, 40, 50"

print( '**'.join( my_str.split(', ')[1 : ] ) )

20**30**40**50


In [16]:
import numpy as np 
a = np.arange(-2, 4, 2) 
b = np.linspace(-2, 4, 4) 
c = np.logspace(-2, 4, 4) 

print(a)
print(b)
print(c)

[-2  0  2]
[-2.  0.  2.  4.]
[1.e-02 1.e+00 1.e+02 1.e+04]


In [17]:
import numpy as np
A = np.arange(1, 20, 2).reshape(5,2)[ : : -1]
print(A)

[[17 19]
 [13 15]
 [ 9 11]
 [ 5  7]
 [ 1  3]]


In [21]:
import numpy as np
A = np.linspace(10, 80, 8).reshape(4,-1)[ : -1]
print(A)

[[10. 20.]
 [30. 40.]
 [50. 60.]]


In [36]:
import numpy as np
A = np.arange(0, 12, 2).reshape(2,3)

"""
[[0, 2, 4], 
[6, 8, 10]]

[[0, 6]
 [2, 8]
 [4, 10]]
"""

print(A)
print("")
print(A.T)
print("")
print(A[A%4 == 0])
print("")
print(A[[0, -1], [1, 2]] )
print("")
print(A[[[1], [-1]], [[0], [1]]])
print("")
print(A.reshape(3,2))
print("")
print(A.sum(axis=1))
print("")
print(A.cumsum())


[[ 0  2  4]
 [ 6  8 10]]

[[ 0  6]
 [ 2  8]
 [ 4 10]]

[0 4 8]

[ 2 10]

[[6]
 [8]]

[[ 0  2]
 [ 4  6]
 [ 8 10]]

[ 6 24]

[ 0  2  6 12 20 30]


In [159]:
# np.round(5 * np.random.rand(3,4)) yes
# np.random.randint(6, size=(3,4)) yes
# np.random.randint(-1, 6, (3,4)) no
# np.random.randint(0, 6, (3,4)) yes
# np.floor(5 * np.random.rand(3,4)) no
# np.ceil(5 * np.random.rand(3,4)) no 
# np.random.randint(6, size=[3,4]) yes
# np.random.randint(6, (3,4)) no
# np.random.randint(5, size=(3,4)) no
# np.random.randint(0, 6, [3,4]) yes

np.random.randint(0, 6, [3,4])


array([[1, 3, 2, 5],
       [1, 0, 5, 1],
       [2, 5, 1, 4]])

In [178]:
A = np.arange(-3, 3).reshape(2,3)
B = np.linspace(0, 3, 3)
#print(A)
#print(B)

print(np.dot(A, B))
print("")


#print(np.dot(B, A)) 
print("ValueError")
print("")

print(np.dot(A, A.T))
print("")

print(np.dot(A[0], B) )
print("")

# print(np.dot(A[:,0], B) )
print("ValueError")
print("")

print(A * A)
print("")

#print(A @ A)
print("ValueError")
print("")

print(A @ A.T)
print("")

print(np.dot(B.T, B))
print("")



[-6.   7.5]

ValueError

[[14 -4]
 [-4  5]]

-6.0

ValueError

[[9 4 1]
 [0 1 4]]

ValueError

[[14 -4]
 [-4  5]]

11.25

