In [3]:
import numpy as np

## Logical Indexing
randArray1 = np.random.rand

cur_shape = tuple(np.random.randint(3, 9, 2))
print(f'Matrix Dimensions: {cur_shape}')

cur_rng = np.random.default_rng()
rnd_array = cur_rng.integers(-5, 5, endpoint=True)
print(f'Current Random Matrix:\n {rnd_array}')

print(f'The number of elements >= 0 {(rnd_array >= 0).sum()}')

Matrix Dimensions: (7, 7)
Current Random Matrix:
 3
The number of elements >= 0 1


In [4]:
curArray0 = np.arange(20).reshape(2,10) #20 numbers in 20 position; they need to match 
print(curArray0)

curArray1 = curArray0.reshape(5,4)
print(curArray1)

curArray2 = curArray0.T.reshape(5,4)
print(curArray2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0 10  1 11]
 [ 2 12  3 13]
 [ 4 14  5 15]
 [ 6 16  7 17]
 [ 8 18  9 19]]


In [5]:
## Element-wise Operations on Arrays 
curArray0 = np.arange(12).reshape(2,6)
print(f'Array with a range of values: {curArray0}')

curArray1 = curArray0*2 # Broadcasting
# curArray1 *= 2
# curArray1 **= 2
print(f'Array 1 = Array 0 *2: {curArray1}')

curArray2 = np.round(10*np.random.rand(2,60))
print(f'Random Array 2: {curArray2}')

print(f'Reshape Array 2: {curArray2.reshape(3,4)}')
print(f'Transpose Array 2: {curArray2.T}')
print(f'Reshape Array 2 Transpose Array 2: {curArray2.T.reshape(3, 4)}')

curArray3 = curArray0 * curArray2
print(f'Element-wise operations on Matrixes: {curArray0}')

curArray4 = curArray0.T
print(f'Shape of Matrix Transpose: {curArray0}')

print(f'Comparing any matixes: {curArray0 > curArray1}')



Array with a range of values: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Array 1 = Array 0 *2: [[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]
Random Array 2: [[ 3.  5.  1.  4.  5.  9.  3.  9.  9.  5.  4.  7.  4.  2.  6.  1.  7.  9.
   1.  2.  4.  0. 10.  9.  4.  6.  2.  8.  2.  5.  5.  4.  2.  5.  2.  6.
  10.  9.  8.  2.  7.  2.  7.  7.  0.  3.  8.  6.  8.  8.  3.  5.  6.  7.
   8.  5.  1.  8.  6.  8.]
 [ 8.  8.  2.  1.  5.  1.  3.  8.  1.  4.  6.  3.  6.  6.  4.  3.  2.  7.
   1.  2.  3.  4.  9.  2.  0.  9.  5.  4.  8. 10.  1.  3.  3.  8.  7.  4.
   2.  3.  0.  4.  4.  0.  4.  8.  4.  7.  7.  6.  6.  1.  3.  3.  3.  3.
   7.  6.  9.  8.  1.  1.]]


ValueError: cannot reshape array of size 120 into shape (3,4)

In [9]:
# Linear Algebra
import numpy as np 
from numpy import linalg

curVec1 = np.linspace(5, 10, 6)
print(f'1D Vector of Equally Spaced Points Vec1 : {curVec1}')

curVec2 = np.arange(0, -6, -1)
print(f'1D Vector of Equally Spaced Points Vec2 : {curVec2}')

cur_rng = np.random.default_rng(5)
#curVec3 = cur_rng.integers(10, 20, curVec)

curMat2 = np.random.randint(10, 20, (2,6))
print(f'2D Matrix of Random Integers: \n {curMat2}')

dotRes1 = np.dot(-5, curVec2)
print(f'Dot product of a vector and scaler number: \n {dotRes1}')

dotRes2 = np.dot(curVec1, curVec2)
print(f'Dot product of a vector and vector: \n {dotRes2}')


1D Vector of Equally Spaced Points Vec1 : [ 5.  6.  7.  8.  9. 10.]
1D Vector of Equally Spaced Points Vec2 : [ 0 -1 -2 -3 -4 -5]
2D Matrix of Random Integers: 
 [[15 14 17 11 12 11]
 [19 15 17 13 17 11]]
Dot product of a vector and scaler number: 
 [ 0  5 10 15 20 25]
Dot product of a vector and vector: 
 -130.0


In [10]:
## Linear Algebra #2

curMat3 = np.arange(-8, 8, 1).reshape(4,-1)
print(f'Matrix Determinant: {np.linalg.det(curMat3)}')

subMat = curMat3[[0, 2], [2, 1]] [[0, 3], [0, 1]]

subMatInv = np.linalg.inv(subMat)
print(f'Verify the Matrix Inversion: \n{np.dot(subMat, subMatInv)}')

c = subMat @ subMatInv
print(f'Matrix Multiplication Using @: \n{c}')

d = np.matmul(subMat, subMatInv)
print(f'Matrix Multiplication Using matmul {d}')

e = subMat * subMatInv
print(f'Element-Wise Matrix Multiplication {e}')

Matrix Determinant: 0.0


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [11]:
# Ay = b
# x = A^-1 * b

coef = np.array([[2, 3], [-3, 4]])
b = np.array([-5, -1])
x = np.linalg.solve(coef, b)

print(f'Solving System of Multiple Equations with Unknowns: {x}')

y = np.dot(np.linalg.inv(coef), b)
print(f'Verifying Solutions of System of Multiple Equations with Unknowns (Matrix Inversion): {y}')

z = np.dot(coef, x) - b
print(f'Verifying Solutions of System of Multiple Equations with Unknowns (Using Matrix Multiplcation): {z}')


#Solve for b 
b = np.dot(coef, x)
print(f'Find B value {b}')

Solving System of Multiple Equations with Unknowns: [-1. -1.]
Verifying Solutions of System of Multiple Equations with Unknowns (Matrix Inversion): [-1. -1.]


In [16]:
import numpy as np
from numpy import linalg

num_var = 3
coef = np.zeros((num_var, num_var))
while np.linalg.det(coef) == 0:
    coef = np.random.randint(-2, 3, (num_var, num_var))

cur_rng = np.random.default_rng()
b = cur_rng.integers(5, size=num_var)

x = np.linalg.solve(coef, b)


print(f'Solving System of Multiple Equations with Unknowns: {x}')

y = np.dot(np.linalg.inv(coef), b)
print(f'Verifying Solutions of System of Multiple Equations with Unknowns (Matrix Inversion): {y}')

z = np.dot(coef, x) - b
print(f'Verifying Solutions of System of Multiple Equations with Unknowns (Using Matrix Multiplcation): {z}')


#Solve for b 
b = np.dot(coef, x)
print(f'Find B value {b}')

Solving System of Multiple Equations with Unknowns: [ 1.75  0.5  -0.25]
Verifying Solutions of System of Multiple Equations with Unknowns (Matrix Inversion): [ 1.75  0.5  -0.25]
Verifying Solutions of System of Multiple Equations with Unknowns (Using Matrix Multiplcation): [0. 0. 0.]
Find B value [4. 1. 2.]
