In [1]:
import numpy as np
# NumPy (Numerical Python)
# - Math: 
# - Bit manipulations
# - Trigonometry
# - Comparison
# - Floating Point

# 4 bits 0 - 15
# 16; 10000
# 17: 10001

# Array Indexing and Slicing 
randArray1 = np.random.randint(10, 201, (5,10), dtype=np.uint8)
print(f'Random Integers Matrix \n {randArray1}')

print(randArray1[1:3, 3:6])
print(randArray1[1:4:2, 3:6])
# rows: 1,3
# col: 2,5
print(randArray1[1::2, 2::3])

print(randArray1[1:,4::3])

# print the values in the row
print(randArray1)

# element at row 0 and col 2 
# element at row 2 and col 6
print(f'Array Indexing: n\ {randArray1[[0, 2], [2,6]]}')

print(f'Array Indexing: n\ {randArray1[[0, 2, -1], [2,6, 2]]}')


# yellow bracket on right is row notation
# yellow bracket on left is col notation
print(f'Array Indexing: n\ {randArray1[[[0, 4, 1], [3,2, 3]], [[2, 5, 2], [-1, 0, -1]]]}')

randArray1[[2, 3], [4,0]] = -200
print(f'Array Modification: n\ {randArray1}')
randArray1[1, -1] = -200
print(f'Array Modification: n\ {randArray1}')


curRng = np.random.default_rng(1)
curMean, curStd = 2, np.sqrt(3)
randArray2 = curRng.normal(loc=curMean, scale=curStd, size=(5,6))
print(f'Random Matrix with Normal Distribution n\{randArray2}')

Random Integers Matrix 
 [[ 55 118  53  23  20 199 147 165  94  36]
 [ 94 194 188 181  76  57 179  89 142  59]
 [147  17 160  23 152  69 103  43  39  47]
 [174 136 196  59  81 170  34  82 163 193]
 [104 164  15 188  38 195  31  98 160 150]]
[[181  76  57]
 [ 23 152  69]]
[[181  76  57]
 [ 59  81 170]]
[[188  57 142]
 [196 170 163]]
[[ 76  89]
 [152  43]
 [ 81  82]
 [ 38  98]]
[[ 55 118  53  23  20 199 147 165  94  36]
 [ 94 194 188 181  76  57 179  89 142  59]
 [147  17 160  23 152  69 103  43  39  47]
 [174 136 196  59  81 170  34  82 163 193]
 [104 164  15 188  38 195  31  98 160 150]]
Array Indexing: n\ [ 53 103]
Array Indexing: n\ [ 53 103  15]
Array Indexing: n\ [[ 53 195 188]
 [193 147 193]]
Array Modification: n\ [[ 55 118  53  23  20 199 147 165  94  36]
 [ 94 194 188 181  76  57 179  89 142  59]
 [147  17 160  23  56  69 103  43  39  47]
 [ 56 136 196  59  81 170  34  82 163 193]
 [104 164  15 188  38 195  31  98 160 150]]
Array Modification: n\ [[ 55 118  53  23  20 199 147 1